[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
# We don't strictly need startCommand if Dockerfile has CMD, but it's good for clarity
startCommand = "node server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
